### ISSUE TITLE
page load modal to display messages

### ISSUE THREAD

**Issue by fredlange** [fredlange/Lightweight-SPA-template#1]
Need a page load modal div to display messages, something like:
```javascript
<script>
	window.onload = function(){
		document.getElementById('button').onclick = function () {
			document.getElementById('modal').style.display = "none"
		};
	};
</script>
```

```css
#modal {
    position: fixed;
    font-family: Arial, Helvetica, sans-serif;
    top: 0;
    left: 0;
    background: rgba(0, 0, 0, 0.8);
    z-index: 99999;
    height: 100%;
    width: 100%;
}
.modalconent {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background: #fff;
    width: 80%;
    padding: 20px;
}
```

```html
<div id="modal">
    <div class="modalconent">
         <h1>Headline</h1>

        <p>Some content</p>
        <button id="button">OK I get it</button>
    </div>
</div>
```
The function must be modular and allow for easy managing.
